modLoader = "javafml"
loaderVersion = "[36,)"
license = "No license. All rights reserved"

[[mods]]
modId = "alphabotany"
version = "${file.jarVersion}"
displayName = "Alpha Botany"
#logoFile = "logo.png"
authors = "Alex3236, standing on the shoulders of giants"
description = '''
Add back some useful blocks for Botania.
Original idea, original code and textures from Extra-Botany and BotaniaNeedSIT.
'''

[[dependencies.alphabotany]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.alphabotany]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"

[[dependencies.alphabotany]]
modId = "extrabotany"
mandatory = true
versionRange = "[1.0,)"
ordering = "NONE"
side = "BOTH"
